# Generated by Django 6.0.3 on 2026-03-29 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='ma_nv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.nhanvien'),
        ),
    ]
