# Generated by Django 6.0.3 on 2026-03-24 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nv', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=255)),
                ('ngay_sinh', models.DateField()),
                ('cccd', models.CharField(max_length=12, unique=True)),
                ('sdt', models.CharField(max_length=15, unique=True)),
                ('chuc_vu', models.CharField(max_length=100)),
                ('vi_tri_vl', models.CharField(max_length=100)),
                ('dia_chi', models.TextField()),
                ('ma_chi_nhanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhan_viens', to='branches.chinhanh')),
            ],
        ),
    ]
